// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbfp7mNVTlqLfMz25ZCdcddXYTNLehBBw',
    appId: '1:721695696296:web:a4aea06b7302bc378ca99d',
    messagingSenderId: '721695696296',
    projectId: 'flutter-animo-eats-d4b36',
    authDomain: 'flutter-animo-eats-d4b36.firebaseapp.com',
    databaseURL: 'https://flutter-animo-eats-d4b36-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-animo-eats-d4b36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLPrwbNmDWo486rcfvScoA4FTMd_XvN1E',
    appId: '1:721695696296:android:7a0f3d33804652788ca99d',
    messagingSenderId: '721695696296',
    projectId: 'flutter-animo-eats-d4b36',
    databaseURL: 'https://flutter-animo-eats-d4b36-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-animo-eats-d4b36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE1-EmIcK5F358eL5NNYGDSOsNYCoZ7pk',
    appId: '1:721695696296:ios:27bb94bc48efa6a18ca99d',
    messagingSenderId: '721695696296',
    projectId: 'flutter-animo-eats-d4b36',
    databaseURL: 'https://flutter-animo-eats-d4b36-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-animo-eats-d4b36.appspot.com',
    iosBundleId: 'com.shokhrukhbek.foodNinja',
  );
}
